version: '2.0'
services:
    app:
        extends:
            file: docker-compose-base.yml
            service: app
        volumes: 
            - .:/usr/src/app
        environment:
            - FLASK_DEBUG=1
            - FLASK_ENV=development
